# This file was generated by GoReleaser. DO NOT EDIT.
cask "sqlstreams" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "8d5162696cae8c237fdbc0364b1e2455167804873f1274b4f052de3e1199caa5"
      url "https://github.com/allegedlyreliable/sqlstreams/releases/download/v#{version}/sqlstreams_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f2a60d7d274ce09eaf00c6ee2e3a43af93f1d3bde9d38f3ad038944d32b88011"
      url "https://github.com/allegedlyreliable/sqlstreams/releases/download/v#{version}/sqlstreams_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8eab2a2e40c8740decc66609b99a54dddc56a3cac6b8bcd4d49b914bf432b874"
      url "https://github.com/allegedlyreliable/sqlstreams/releases/download/v#{version}/sqlstreams_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e2f85f5be89e92166801848a835adece055a312b8e8eb3e78bc9fd322de2d627"
      url "https://github.com/allegedlyreliable/sqlstreams/releases/download/v#{version}/sqlstreams_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sqlstreams"
  desc "CLI for SQLStreams, the Postgres-backed message log"
  homepage "https://sqlstreams.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sqlstreams"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sqlstreams"]
    end
  end

  # No zap stanza required
end
