# This file was generated by GoReleaser. DO NOT EDIT.
cask "sqlstreams" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "03ff7e6aba95d6c1121dba40f1758b7a5f00fde3c36517a7db874072790bb198"
      url "https://github.com/allegedlyreliable/sqlstreams/releases/download/v#{version}/sqlstreams_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "122f7d0b3ae0926567daca3c9c1d9a87c6dd729f707d1deeb6635a3f4e4b5f18"
      url "https://github.com/allegedlyreliable/sqlstreams/releases/download/v#{version}/sqlstreams_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "119c5fac1d1977f51b99e5fd81fdc5ccb1c388fe8452bde619867557f6a2a7c9"
      url "https://github.com/allegedlyreliable/sqlstreams/releases/download/v#{version}/sqlstreams_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2ebedc142a51b662f6b61edf72c7b93b0945a346e734ebe9be413dd89e1760f2"
      url "https://github.com/allegedlyreliable/sqlstreams/releases/download/v#{version}/sqlstreams_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sqlstreams"
  desc "CLI for SQLStreams, the Postgres-backed message log"
  homepage "https://sqlstreams.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sqlstreams"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sqlstreams"]
    end
  end

  # No zap stanza required
end
