# This file was generated by GoReleaser. DO NOT EDIT.
cask "sqlstreams" do
  version "0.1.5"

  on_macos do
    on_arm do
      sha256 "808cc0b07b1bb9ff772e854b7d30b8198ef490e9148e4d52c10e82bfe57fdef7"
      url "https://github.com/allegedlyreliable/sqlstreams/releases/download/v#{version}/sqlstreams_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d4d8ea55325be89bae4a5f6b172b96f2763c37730a045ba326b14579615cb1c2"
      url "https://github.com/allegedlyreliable/sqlstreams/releases/download/v#{version}/sqlstreams_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ff55719f1a3ce7ec5d9d7bfa98221947060abf6328331f2796a433e11a803756"
      url "https://github.com/allegedlyreliable/sqlstreams/releases/download/v#{version}/sqlstreams_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0dda422ae43a277ea4fbb6ce4736f3167b31bed9d8088f02c6bd6215444a3351"
      url "https://github.com/allegedlyreliable/sqlstreams/releases/download/v#{version}/sqlstreams_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sqlstreams"
  desc "CLI for SQLStreams, the Postgres-backed message log"
  homepage "https://sqlstreams.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sqlstreams"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sqlstreams"]
    end
  end

  # No zap stanza required
end
